# Generated by Django 2.1rc1 on 2018-08-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_No', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=25)),
                ('Last_name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=50)),
                ('Patient_Age', models.CharField(max_length=10)),
                ('Gender', models.TextField(max_length=10)),
                ('Patient_Address', models.TextField(max_length=200)),
                ('Contact', models.TextField(max_length=50)),
                ('Room', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
