# Generated by Django 2.1rc1 on 2018-08-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Date',
            new_name='date',
        ),
    ]
