# Generated by Django 2.1rc1 on 2018-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20180809_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
    ]
