# Generated by Django 2.1rc1 on 2018-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20180810_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Contact',
            field=models.CharField(max_length=50),
        ),
    ]
